#!/usr/bin/env python3
"""
Fisheye / All-Sky Camera Dewarper
===================================
Converts fisheye (equidistant or equisolid) frames to standard rectilinear
perspective projection, enabling the detection pipeline to work with 360°
dome cameras without distortion bias.

Supports:
  - Equidistant projection (most fisheye lenses)
  - Equisolid (equal-area) projection
  - Orthographic projection
  - Custom calibration from OpenCV calibrateCamera()

Usage:
  dewarper = FisheyeDewarper(frame_w=1280, frame_h=1280, fov_deg=180)
  dewarper.build_maps()
  rect_frame = dewarper.dewarp(fisheye_frame)
"""
import numpy as np
import cv2
import json
from pathlib import Path


class FisheyeDewarper:
    """
    Dewarp a fisheye camera frame to a rectilinear perspective view.
    Uses precomputed remap tables for efficient per-frame processing.
    """

    PROJECTIONS = ('equidistant', 'equisolid', 'orthographic', 'stereographic')

    def __init__(
        self,
        frame_w: int,
        frame_h: int,
        fov_deg: float = 180.0,
        projection: str = 'equidistant',
        cx: float = None,
        cy: float = None,
        output_w: int = 1280,
        output_h: int = 720,
        output_fov_deg: float = 120.0,
    ):
        assert projection in self.PROJECTIONS, f'Unknown projection: {projection}'
        self.frame_w     = frame_w
        self.frame_h     = frame_h
        self.fov_deg     = fov_deg
        self.projection  = projection
        self.cx          = cx if cx is not None else frame_w / 2
        self.cy          = cy if cy is not None else frame_h / 2
        self.output_w    = output_w
        self.output_h    = output_h
        self.output_fov  = output_fov_deg
        self._map1       = None
        self._map2       = None

    def build_maps(self):
        """Precompute the remap tables. Call once before processing frames."""
        fov_rad  = np.radians(self.fov_deg)
        out_fov  = np.radians(self.output_fov)
        out_w, out_h = self.output_w, self.output_h

        # Output pixel grid — normalised screen coords
        xs = np.linspace(-1, 1, out_w)
        ys = np.linspace(-1, 1, out_h)
        grid_x, grid_y = np.meshgrid(xs, ys)

        # Convert output pixel → 3D ray direction (pinhole model)
        fx = 1.0 / np.tan(out_fov / 2)
        ray_x = grid_x / fx
        ray_y = grid_y / fx * (out_h / out_w)
        ray_z = np.ones_like(ray_x)
        ray_len = np.sqrt(ray_x**2 + ray_y**2 + ray_z**2)
        ray_x /= ray_len
        ray_y /= ray_len
        ray_z /= ray_len

        # Compute angle from optical axis (theta)
        theta = np.arccos(np.clip(ray_z, -1, 1))
        phi   = np.arctan2(ray_y, ray_x)

        # Map theta → radius in fisheye image (mm → normalised)
        R_max = min(self.cx, self.cy)  # max radius in source image
        if self.projection == 'equidistant':
            r = (theta / (fov_rad / 2)) * R_max
        elif self.projection == 'equisolid':
            r = 2 * np.sin(theta / 2) / (2 * np.sin(fov_rad / 4)) * R_max
        elif self.projection == 'orthographic':
            r = np.sin(theta) / np.sin(fov_rad / 2) * R_max
        elif self.projection == 'stereographic':
            r = 2 * np.tan(theta / 2) / (2 * np.tan(fov_rad / 4)) * R_max
        else:
            r = (theta / (fov_rad / 2)) * R_max

        # Convert back to source pixel coordinates
        src_x = self.cx + r * np.cos(phi)
        src_y = self.cy + r * np.sin(phi)

        self._map1 = src_x.astype(np.float32)
        self._map2 = src_y.astype(np.float32)

    def dewarp(self, frame: np.ndarray) -> np.ndarray:
        """Dewarp a fisheye frame. Returns rectilinear frame."""
        if self._map1 is None:
            self.build_maps()
        return cv2.remap(frame, self._map1, self._map2, cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT)

    def save_maps(self, path: str):
        """Cache remap tables to disk for fast startup."""
        np.savez(path, map1=self._map1, map2=self._map2)

    def load_maps(self, path: str) -> bool:
        """Load cached remap tables."""
        p = Path(path + '.npz')
        if p.exists():
            data = np.load(str(p))
            self._map1 = data['map1']
            self._map2 = data['map2']
            return True
        return False

    @classmethod
    def from_calibration(cls, calibration_file: str, output_w=1280, output_h=720):
        """
        Create a dewarper from an OpenCV calibration file (JSON).
        The calibration file should contain: camera_matrix, dist_coeffs, image_size
        Typically generated by: cv2.calibrateCamera() with a checkerboard.
        """
        with open(calibration_file) as f:
            cal = json.load(f)
        K = np.array(cal['camera_matrix'])
        D = np.array(cal['dist_coeffs'])
        w, h = cal['image_size']
        inst = cls(frame_w=w, frame_h=h, output_w=output_w, output_h=output_h)
        # Use OpenCV's built-in fisheye undistortion
        new_K = cv2.fisheye.estimateNewCameraMatrixForUndistortRectify(K, D, (w, h), np.eye(3), balance=0.5)
        map1, map2 = cv2.fisheye.initUndistortRectifyMap(K, D, np.eye(3), new_K, (output_w, output_h), cv2.CV_16SC2)
        inst._map1 = map1
        inst._map2 = map2
        return inst
